# Generated by Django 5.2.1 on 2025-06-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название слайда')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Картина слайда')),
            ],
        ),
    ]
